# Generated by Django 2.2 on 2020-04-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_iris_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
        migrations.RenameField(
            model_name='iris',
            old_name='peatl_width',
            new_name='petal_width',
        ),
    ]
