From python:3.7

RUN apt-get update
RUN apt-get -y install vim

RUN pip install django==2.1.7
RUN pip install djangorestframework==3.9.2
RUN pip install psycopg2==2.7.6
RUN pip install psycopg2-binary==2.7.7
RUN pip install django-cors-headers==2.5.2
RUN pip install django-filter


## ----------------
## create Django App
## ----------------

RUN django-admin startproject django_rest_framework
WORKDIR /django_rest_framework
RUN python manage.py startapp predict_iris

